### ISSUE TITLE
infomation to start server on Mac

### ISSUE THREAD

**Issue by NarubyRiverlione** [OpenLWR/OpenLWR-Server#19]
No a bug, just the command that I needed to do to get the server started on Mac.
Maybee you can add them to the readme

cd into the unpacked server directory
python3 -m venv .
source bin/activate
python3 -m pip -r requirements.txt

Then I needed one extra install
python3 -m pip install matplotlib

and now run the server with:  python3 main.py

**Comment by watchful5406** [comment]
@SakuruWasTaken can you verify this is required

**Comment by SakuruWasTaken** [comment]
the matplotlib dependency shouldn't be required anymore (was accidentally left in for testing purposes)

i will test the server on mac and see if these are required in my case, then i will make a note of it in the readme

**Comment by SakuruWasTaken** [comment]
added new instructions to readme
